services:
  fastapi:
    build: 
      target: fastapi
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - alembic
      - postgres
    restart: unless-stopped

  alembic:
    build: 
      target: alembic
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - .:/app
    depends_on:
      - postgres
        
  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./core/postgres/__data__:/var/lib/postgresql/data
    restart: unless-stopped